package export

import (
	"encoding/csv"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"polytracker/internal/db"
)

// Exporter handles exporting data to various formats
type Exporter struct {
	exportDir string
}

// NewExporter creates a new Exporter with the given export directory
func NewExporter(exportDir string) *Exporter {
	if exportDir == "" {
		exportDir = "exports"
	}
	return &Exporter{exportDir: exportDir}
}

// EnsureExportDir creates the export directory if it doesn't exist
func (e *Exporter) EnsureExportDir() error {
	return os.MkdirAll(e.exportDir, 0755)
}

// ExportLeaderboardCSV exports the leaderboard data to a CSV file
func (e *Exporter) ExportLeaderboardCSV(traders []db.Trader, filename string) (string, error) {
	if err := e.EnsureExportDir(); err != nil {
		return "", fmt.Errorf("failed to create export directory: %w", err)
	}

	if filename == "" {
		filename = fmt.Sprintf("leaderboard_%s.csv", time.Now().Format("20060102_150405"))
	}

	// Ensure .csv extension
	if !strings.HasSuffix(strings.ToLower(filename), ".csv") {
		filename += ".csv"
	}

	path := filepath.Join(e.exportDir, filename)

	file, err := os.Create(path)
	if err != nil {
		return "", fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	writer := csv.NewWriter(file)
	defer writer.Flush()

	// Write header
	header := []string{"Rank", "Address", "Username", "Win Rate (%)", "P&L ($)", "ROI (%)", "Volume ($)", "Last Scanned"}
	if err := writer.Write(header); err != nil {
		return "", fmt.Errorf("failed to write header: %w", err)
	}

	// Write data rows
	for i, t := range traders {
		row := []string{
			fmt.Sprintf("%d", i+1),
			t.Address,
			t.Username,
			fmt.Sprintf("%.2f", t.WinRate*100),
			fmt.Sprintf("%.2f", t.ProfitLoss),
			fmt.Sprintf("%.2f", t.ROI*100),
			fmt.Sprintf("%.2f", t.Volume),
			t.LastScanned.Format("2006-01-02 15:04:05"),
		}
		if err := writer.Write(row); err != nil {
			return "", fmt.Errorf("failed to write row %d: %w", i+1, err)
		}
	}

	return path, nil
}

// ExportThesisMarkdown exports a trading thesis to a markdown file
func (e *Exporter) ExportThesisMarkdown(trader *db.Trader, thesis string, filename string) (string, error) {
	if err := e.EnsureExportDir(); err != nil {
		return "", fmt.Errorf("failed to create export directory: %w", err)
	}

	if thesis == "" {
		return "", fmt.Errorf("no thesis content to export")
	}

	if filename == "" {
		shortAddr := trader.Address
		if len(shortAddr) > 10 {
			shortAddr = shortAddr[:10]
		}
		filename = fmt.Sprintf("thesis_%s_%s.md", shortAddr, time.Now().Format("20060102_150405"))
	}

	// Ensure .md extension
	if !strings.HasSuffix(strings.ToLower(filename), ".md") {
		filename += ".md"
	}

	path := filepath.Join(e.exportDir, filename)

	var content strings.Builder

	// Write header with metadata
	content.WriteString(fmt.Sprintf("# Trading Thesis: %s\n\n", trader.Address))
	if trader.Username != "" {
		content.WriteString(fmt.Sprintf("**Trader:** %s\n\n", trader.Username))
	}
	content.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().Format("2006-01-02 15:04:05")))

	// Write trader stats summary
	content.WriteString("## Trader Summary\n\n")
	content.WriteString(fmt.Sprintf("| Metric | Value |\n"))
	content.WriteString(fmt.Sprintf("|--------|-------|\n"))
	content.WriteString(fmt.Sprintf("| Win Rate | %.2f%% |\n", trader.WinRate*100))
	content.WriteString(fmt.Sprintf("| P&L | $%.2f |\n", trader.ProfitLoss))
	content.WriteString(fmt.Sprintf("| ROI | %.2f%% |\n", trader.ROI*100))
	content.WriteString(fmt.Sprintf("| Volume | $%.2f |\n", trader.Volume))
	content.WriteString("\n---\n\n")

	// Write thesis content
	content.WriteString("## Analysis\n\n")
	content.WriteString(thesis)

	// Write footer
	content.WriteString("\n\n---\n")
	content.WriteString(fmt.Sprintf("*Generated by Polytracker on %s*\n", time.Now().Format("2006-01-02 15:04:05")))

	if err := os.WriteFile(path, []byte(content.String()), 0644); err != nil {
		return "", fmt.Errorf("failed to write file: %w", err)
	}

	return path, nil
}

// ExportAnalysisFromDB exports an analysis from the database
func (e *Exporter) ExportAnalysisFromDB(database *db.DB, traderAddress string, filename string) (string, error) {
	trader, err := database.GetTrader(traderAddress)
	if err != nil {
		return "", fmt.Errorf("failed to get trader: %w", err)
	}
	if trader == nil {
		return "", fmt.Errorf("trader not found: %s", traderAddress)
	}

	analysis, err := database.GetAnalysisByTrader(traderAddress)
	if err != nil {
		return "", fmt.Errorf("failed to get analysis: %w", err)
	}
	if analysis == nil {
		return "", fmt.Errorf("no analysis found for trader: %s", traderAddress)
	}

	return e.ExportThesisMarkdown(trader, analysis.Thesis, filename)
}
